name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: ITHelpDeskSupport
  PYTHON_VERSION: '3.12'

on:
  push:
    branches: [ minimal-azure-test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps (backend)
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Debug show what will be deployed
        run: |
          echo "Root:"
          ls -la
          echo "Backend:"
          ls -la backend || true
          echo "Top of backend/app.py:"
          sed -n '1,80p' backend/app.py || true

      - name: Package backend (ZipDeploy)
        run: |
          cd backend
          zip -r ../site.zip . -x "**/.git/**" "**/__pycache__/**"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App (ZipDeploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: site.zip