
name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: ITHelpDeskSupport
  PYTHON_VERSION: '3.12'

on:
  push:
    branches: [ minimal-azure-test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Package backend
        run: |
            cd backend
            zip -r ../site.zip . -x "**/.git/**" "**/__pycache__/**"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site.tar.gz
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: .

      - name: Deploy to Azure Web App (Tar.gzDeploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: site.tar.gz
          clean: true
          restart: true

