name: Build and deploy Python app to Azure Web App - ITHelpDeskSupport

on:
  push:
    branches: [ minimal-azure-test ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Clean .python_packages
        working-directory: backend
        run: rm -rf .python_packages

      # 1) Install a known-good PyTorch CPU wheel for Py3.12
      - name: Preinstall torch (CPU) into .python_packages
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --only-binary=:all: \
            --extra-index-url https://download.pytorch.org/whl/cpu \
            --target ./.python_packages/lib/site-packages \
            torch==2.2.2

      # 2) Lock torch so the resolver won't try to change it
      - name: Write constraints
        working-directory: backend
        run: echo "torch==2.2.2" > constraints.txt

      # 3) Install sentence-transformers WITHOUT deps (so it won't re-pull torch)
      - name: Install sentence-transformers (no-deps)
        working-directory: backend
        run: |
          pip install --no-cache-dir --only-binary=:all: \
            --target ./.python_packages/lib/site-packages \
            sentence-transformers==5.0.0 --no-deps

      # Ensure Flask-Cors is present (the missing import you saw)
      - name: Ensure Flask-Cors is vendored
        working-directory: backend
        run: |
          pip install --no-cache-dir --only-binary=:all: \
            --target ./.python_packages/lib/site-packages \
            flask-cors==6.0.1

      - name: Verify flask_cors present
        working-directory: backend
        shell: bash
        run: |
          python -c 'import os; p=".python_packages/lib/site-packages/flask_cors"; print("flask_cors:", "FOUND" if os.path.isdir(p) else "MISSING")'
          ls -ld ./.python_packages/lib/site-packages/flask_cors || true


      # 4) Install the REST of requirements (exclude torch & sentence-transformers)
      #    as portable manylinux_2_17 wheels to avoid GLIBC issues
      - name: Make filtered requirements (exclude torch & sentence-transformers)
        working-directory: backend
        run: |
          grep -viE '^(torch|sentence-transformers)(==|>=|<=|~=|>|<)' requirements.txt > req.filtered.txt
          echo "Using filtered requirements:"
          cat req.filtered.txt

      - name: Install remaining deps into .python_packages (manylinux_2_17)
        working-directory: backend
        run: |
          pip install --upgrade --no-cache-dir --only-binary=:all: \
            --platform manylinux_2_17_x86_64 --implementation cp --python-version 3.12 --abi cp312 \
            --extra-index-url https://download.pytorch.org/whl/cpu \
            --constraint constraints.txt \
            --target ./.python_packages/lib/site-packages \
            -r req.filtered.txt

      # Safety: ensure no Python2 'uuid' backport ever sneaks in
      - name: Remove uuid backport if present
        working-directory: backend
        run: |
          rm -f ./.python_packages/lib/site-packages/uuid.py \
                ./.python_packages/lib/site-packages/uuid.pyc || true

      # 5) Zip the *contents* of backend so files are at the ZIP ROOT
      - name: Create deployment zip
        working-directory: backend
        run: zip -r ../app.zip .

      - name: Deploy to Azure Web App (publish profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ITHelpDeskSupport'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: app.zip


