name: Build and deploy Python app to Azure Web App - ITHelpDeskSupport

on:
  push:
    branches: [ minimal-azure-test ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Clean .python_packages
        working-directory: backend
        run: rm -rf .python_packages

      # ✅ Install PyTorch CPU wheel that exists for Python 3.12 and manylinux_2_17
      - name: Preinstall torch (CPU) into .python_packages
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --only-binary=:all: \
            --platform manylinux_2_17_x86_64 --implementation cp --python-version 3.12 --abi cp312 \
            --extra-index-url https://download.pytorch.org/whl/cpu \
            --target ./.python_packages/lib/site-packages \
            torch==2.3.1

      # Install the rest of your deps as portable wheels
      - name: Install deps into .python_packages (manylinux_2_17)
        working-directory: backend
        run: |
          pip install --upgrade --no-cache-dir --only-binary=:all: \
            --platform manylinux_2_17_x86_64 --implementation cp --python-version 3.12 --abi cp312 \
            --target ./.python_packages/lib/site-packages \
            -r requirements.txt

      # Safety: make sure no Python2 backport shadows stdlib
      - name: Remove uuid backport if present
        working-directory: backend
        run: |
          rm -f ./.python_packages/lib/site-packages/uuid.py \
                ./.python_packages/lib/site-packages/uuid.pyc || true

      # Zip the *contents* of backend so run.py, requirements.txt, .python_packages are at ZIP ROOT
      - name: Create deployment zip
        working-directory: backend
        run: zip -r ../app.zip .

      - name: Deploy to Azure Web App (publish profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ITHelpDeskSupport'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: app.zip
