name: Build and deploy Python app to Azure Web App - ITHelpDeskSupport

on:
  push:
    branches: [ minimal-azure-test ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Clean any previous vendored deps (fresh build each time)
      - name: Clean .python_packages
        working-directory: backend
        run: rm -rf .python_packages

      # Install dependencies into the package (no Oryx needed)
      - name: Install deps into .python_packages
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --no-cache-dir \
            --target ./.python_packages/lib/site-packages \
            -r requirements.txt

      # Safety: ensure no third-party uuid backport shadows stdlib on Py3.12
      - name: Remove Python-2 uuid backport if present
        working-directory: backend
        run: |
          rm -f ./.python_packages/lib/site-packages/uuid.py \
                ./.python_packages/lib/site-packages/uuid.pyc || true

      # Zip the *contents* of backend so run.py, requirements.txt, .python_packages are at ZIP ROOT
      - name: Create deployment zip
        working-directory: backend
        run: zip -r ../app.zip .

      - name: Deploy to Azure Web App (publish profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ITHelpDeskSupport'
          slot-name: 'production'     # default slot
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: app.zip
