name: Build and deploy Python app to Azure Web App - ITHelpDeskSupport

on:
  push:
    branches: [ minimal-azure-test ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install ALL backend deps into the app folder (portable)
      - name: Vendor dependencies into .python_packages
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install --target ./.python_packages/lib/site-packages -r requirements.txt

      # Create a single deployable zip where the ZIP ROOT contains run.py, app.py, requirements.txt, and .python_packages
      - name: Create deployment zip
        working-directory: backend
        run: |
          zip -r ../app.zip .  # zips the *contents* of backend (good)

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_15FD0CEF8FBA4AA484B5AAADADC11B41 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0F24001AF8D434FA7EC3E96B1C3DE60 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_657C17FD236742CD93B8BAFEDF472CEA }}

      - name: Deploy to Azure Web App (zip)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ITHelpDeskSupport'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: app.zip
