name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: ITHelpDeskSupport
  PYTHON_VERSION: '3.12'

on:
  push:
    branches: [ minimal-azure-test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # optional CI sanity (doesn't affect Azure build)
      - name: Install deps (backend)
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Package backend (flat zip)
        run: |
          cd backend
          zip -r ../site.zip . -x "**/.git/**" "**/__pycache__/**"

      - name: Debug zip contents
        run: |
          unzip -l site.zip | tail -n 40

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      # (Re)create the flat zip from backend
      - name: Package backend (flat zip)
        run: |
          cd backend
          zip -r ../site.zip . -x "**/.git/**" "**/__pycache__/**"

      - name: Deploy to Azure Web App (ZipDeploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: site.zip
          type: zip            # 👈 force ZipDeploy instead of OneDeploy
          clean: true
          restart: true        # 👈 restart app after deploy
