name: Build and deploy Python app to Azure Web App - ITHelpDeskSupport

on:
  push:
    branches: [ minimal-azure-test ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Clean .python_packages
        working-directory: backend
        run: rm -rf .python_packages

      # 1) Preinstall a known-good PyTorch CPU wheel for Py3.12
      - name: Preinstall torch (CPU) into .python_packages
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --only-binary=:all: \
            --extra-index-url https://download.pytorch.org/whl/cpu \
            --target ./.python_packages/lib/site-packages \
            torch==2.2.2

      # 2) Lock torch so the resolver doesn't try to touch it
      - name: Write constraints
        working-directory: backend
        run: echo "torch==2.2.2" > constraints.txt

      # 3) Install the rest (NO --platform/--abi flags), still allow the torch index
      - name: Install deps into .python_packages
        working-directory: backend
        run: |
          pip install --upgrade --no-cache-dir --only-binary=:all: \
            --extra-index-url https://download.pytorch.org/whl/cpu \
            --constraint constraints.txt \
            --target ./.python_packages/lib/site-packages \
            -r requirements.txt

      # Safety: ensure no Python-2 uuid backport slipped in
      - name: Remove uuid backport if present
        working-directory: backend
        run: |
          rm -f ./.python_packages/lib/site-packages/uuid.py \
                ./.python_packages/lib/site-packages/uuid.pyc || true

      # 4) Create deployable zip with backend contents at the ZIP ROOT
      - name: Create deployment zip
        working-directory: backend
        run: zip -r ../app.zip .

      - name: Deploy to Azure Web App (publish profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ITHelpDeskSupport'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: app.zip
